### ISSUE TITLE
Incomplete Playlist on Mobile

### ISSUE THREAD

**Issue by eirinym** [nonnullish/share-liked-songs#2]
I've noticed that when I create the playlist from my liked songs, it does seem to complete and show correctly on the app for my laptop and desktop (Mac and Windows), but when I use the Spotify app on my mobile devices, I'm only seeing 500 of the songs show up, the most recent ones specifically. I'm not sure if this is a Spotify app issue beyond your control, maybe it is, but I'm wondering what might be causing that. Just thought I would mention this and see if it can be reproduced. It'd need a playlist that is longer than 500 songs, however.

**Comment by nonnullish** [comment]
Hi, hmm if it does show up properly on your desktop then I suppose that's some kind of a limitation enforced by the mobile app and I can't do much about it. I can't find any info about it online though, so I'm not sure what's the cause of it. But thanks for letting me know!
